title: A Planning Ontology to Represent and Exploit Planning Knowledge for Performance Efficiency

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
url:              https://g-nitin.github.io/ontology-website/
baseurl:          https://g-nitin.github.io/ontology-website/

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:          https://g-nitin.github.io/ontology-website/
