title: A Planning Ontology to Represent and Exploit Planning Knowledge for Performance Efficiency

# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
url:              https://github.com/ai4society/planning-ontology/
baseurl:          https://github.com/ai4society/planning-ontology/

paginate:         5

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:          https://ai4society.github.io/planning-ontology/
